name: kickspremium_mobile
description: "KicksPremium Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  flutter_riverpod: ^3.2.0
  go_router: ^17.0.1
  google_fonts: ^7.0.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  flutter_stripe: ^12.2.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/env